//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectProyectoLaberinto.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntuaciones
    {
        public long IdPuntuaciones { get; set; }
        public long IdUsuario { get; set; }
        public byte Dificultad { get; set; }
        public decimal Puntuacion { get; set; }
        public System.DateTime Tiempo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
